### ISSUE TITLE
Update RemoteAddressSniff

### ISSUE THREAD

**Issue by ghost** [serundeputy/coder#1]
The [RemoteAddressSniff](https://github.com/serundeputy/coder/blob/1.x-1.x/coder_sniffer/Backdrop/Sniffs/Semantics/RemoteAddressSniff.php#L45) should be updated to account for situations where `$_SERVER['REMOTE_ADDR']` is being assigned a value, rather than calling its value. E.g. https://github.com/backdrop-contrib/b/blob/1.x-1.x/b.php#L121

Maybe make it so that if `$_SERVER['REMOTE_ADDR']` is followed by an `=` sign, then since you're setting the value the error shouldn't apply...?

**Comment by serundeputy** [comment]
Looks like in the case if `b` the funciton `ip_address()` returns `127.0.0.1` anyway, so the `phpcs` suggestion is a good one.

We should use the `ip_address` function in the `b` code.

**Comment by ghost** [comment]
Is this what you mean?

`$_SERVER['REMOTE_ADDR'] = ip_address();`

Because that still causes the error:

> Use the function ip_address() instead of $_SERVER['REMOTE_ADDR']

I think what it's saying is we should do this:

`ip_address() = '127.0.0.1';`

But of course that doesn't work because `ip_address()` is a getter function, not a setter. So I think Coder needs to be fixed for this situation.

**Comment by ghost** [comment]
If Coder does need to be fixed, that makes me wonder whether the same fix should be applied to [Coder Review](https://github.com/backdrop-contrib/coder_review) as well? If so, is there a way we can de-duplicate the work by having Coder Review depend on Coder, or abstract the sniffs out to another project/module and then have both Coder Review and Coder depend on that?

**Comment by serundeputy** [comment]
>$_SERVER['REMOTE_ADDR'] = ip_address();

yes; that is what I meant, but now that i see how ridiculous a suggestion that was. :laughing: 

I still think the advice `coder` is giving is good advice and that `b` is an edge case as it is running as a client and does not have the `$_SERVER` vars populated as a backdrop site would ... so this is like a  0.01% use case.

- [ ] The easiest course of action is leave it as is.
  * good advice in general (ppl other than cli clients should not be setting `$_SERVER` vars)
- [ ] We could do some regex or some check as you've suggested to make sure the string is not followed by ` =`
  * I don't want to encourage people to set/reset a `$_SERVER` var though

In regards to duplication of effort in `coder_review` there are possibilities.

- [ ] Send the same PR here as a PR to the `coder_review` repo
  * this is the easiest.

Historical Note for Context
----------------------------------

This repo started as a fork of `coder_review` and I took out all the gui stuff so I can run it cli for testing without a bunch of other code I don't need/want.

**Comment by ghost** [comment]
Cool, that sounds fine to leave as-is here and just tell PHPCS to ignore that line in `b`.
