### ISSUE TITLE
Most of the module's files are missing

### ISSUE THREAD

**Issue by jenlampton** [serundeputy/coder#4]
It looks like this module is missing most of its files. Can we add them back? 

We should also give @docwilmot credit for being the current maintainer of all those files :)

**Comment by serundeputy** [comment]
this project does not need these files this is for cli and CI runs only and as such those files were purposely removed.

We can add @docwilmot in the credits section.

**Comment by jenlampton** [comment]
Ah, if it's not a copy of the module it needs a new info file. That file
says it's the module.

**Comment by serundeputy** [comment]
There is no info file in this repo.

**Comment by jenlampton** [comment]
The readme (not info file) is what says that this is a module. You know... that thing people read when they go "what the heck is this thing?" :)

**Comment by serundeputy** [comment]
Don't be rude now; it wasn't the README.md (which you referred to as an info file), it was the description, so you can see where the confusion came in.

Anywho, fixed: `Developer tool which reviews your code identifying coding style problems and where updates to the API are required.`

**Comment by jenlampton** [comment]
yes, responding to github issues from a phone is probably not the best idea... I was really confused when I was looking for the coder module, and couldn't find it. I found this thing, which is called coder, but is not a module, and the thing I did want wasn't called coder anymore, but was the module I was looking for. It's all a bit of a mess!

**Comment by docwilmot** [comment]
I've split Coder into Coder Upgrade and Coder Review. They do different things and I wants them at different times of my life.

**Comment by jenlampton** [comment]
I am going to create an (empty) repo in the contrib group that lets people know, and points to the new separate repos. It took me a while to figure out what was going on -- for months I thought we just didn't have a version of coder yet for Backdrop :/

edit: Here's the repo https://github.com/backdrop-contrib/coder 
@docwilmot I'm going to make you a maintainer so you can update the docs if you want (but don't feel obligated if you don't want)
